### ISSUE TITLE
Wattometer plugin settings not available after installation

### ISSUE THREAD

**Issue by Cloud-Tickler** [RealTryZ/Wattometer#1]
I would like to try this great plugin. Sadly, after installing it via the plugin manager and also directly via the URL, the setting tab stays empty. Here`s a screenshot and the systeminfo files. Maybe you could take a look. 

Regards

Dennis

![Settings_paget](https://github.com/RealTryZ/Wattometer/assets/127838436/86ea0dcc-00c5-4e8c-b131-559993783480)
[octoprint-systeminfo-20230725154327.zip](https://github.com/RealTryZ/Wattometer/files/12161888/octoprint-systeminfo-20230725154327.zip)

**Comment by RealTryZ** [comment]
Thanks for the notice, will look into it.

**Comment by RealTryZ** [comment]
The plugin works now as expected. You might have to reinstall.
Enjoy!

**Comment by Cloud-Tickler** [comment]
Perfect. Thank you so much. It's working. I'm using a FRITZ!DECT 210. So you could add this to the description, that it is also compatible.
![Working_021](https://github.com/RealTryZ/Wattometer/assets/127838436/5cb12412-1b6c-4f1b-8ca7-cf04efdd641d)

**Comment by RealTryZ** [comment]
Thanks for the hint, will add it :)
