### ISSUE TITLE
No Readout from Dect200

### ISSUE THREAD

**Issue by sello89** [RealTryZ/Wattometer#2]
Hello,

i tried everything to connect my Dect200.

username password AIN everything is correct but still no connection ??? 

where could the problem be ?

**Comment by RealTryZ** [comment]
Hey,

just to be sure, have you fixed it?

**Comment by sello89** [comment]
Yes it is working :)
Is it correct that only Watts are displayed when the print job running?

It would be great if it could be at the status bar.

right now its showing nothing ?? 30 Minutes ago it was working … 
![IMG_4996](https://github.com/RealTryZ/Wattometer/assets/49493020/37d08787-48b4-4ae2-9ca6-c26655516442)

**Comment by RealTryZ** [comment]
Yes that is correct, the plugin is supposed to measure the watt a print actually needed, therefore the measurements starts when a print is started and ends when a print ended. At the end you will have the Total Power Usage in Wh of this print.

The status bar is a great idea will add the feature in the following days.

Have you reloaded the page in this time?

**Comment by sello89** [comment]
Ok good to know. You should ad this information to the Wiki from the plugin. 

Yes reloaded the page but still no readout from the dect 200.

I try to do a log from the plugin. Hopefully this work.

**Comment by sello89** [comment]
It would be better if the tool always reads the power. But for the power consumtion just take the time from start till the end from the print.

**Comment by RealTryZ** [comment]
> Ok good to know. You should ad this information to the Wiki from the plugin.
> 
> Yes reloaded the page but still no readout from the dect 200.
> 
> I try to do a log from the plugin. Hopefully this work.

Would be great thank you

**Comment by RealTryZ** [comment]
Hey sello,
I've reworked the plugin a little and now it always displays the power-usage in the graph. When a print starts, the total power-usage starts counting. This info will be also displayed right above the progress bar in the state-window.
Hope you like the changes :)

**Comment by sello89** [comment]
Hey
cool looks nice !
Readout is working!

Will try the rest within the next prints.

thanks for your work!
