### ISSUE TITLE
Total Power Usage is reseted after end of print

### ISSUE THREAD

**Issue by Cloud-Tickler** [RealTryZ/Wattometer#3]
Hey Pascal,
thanks again for this wonderful plugin. I don't know your specific use case for it. Right now, as far as I can see, the total power usage gets reseted after the print stops. So, when you come back to your print half an hour later, you won't see the used power anymore. Only if you watch it till the end and write the numbers down. Can I find this data somewhere in the log files? Or would it be an option to reset the value before the start of a new print, and not with the end the actual one? So one could still see those numbers. 
Thanks in advance
Dennis
PS I haven't found an option to open a feature request, so I had to create an issue.

**Comment by RealTryZ** [comment]
Hey Dennis,
I think you're totally right. The way the plugin works right now is a bit silly. I've also thought of this and will change it this weekend :)
Also will look into feature requests.
Thank you for letting me notice.
Kind regards
Pascal

**Comment by RealTryZ** [comment]
Hey Dennis,
I've changed the plugin a litte and it now only resets the total power usage if you start another print.
Regarding the feature request, I will look into it on another day.
Hope you like the change :)

**Comment by Cloud-Tickler** [comment]
Hey Pascal,
have you uploaded the new version? I can't see an update that I could use for a test.
Thanks.
Regards
Dennis

**Comment by Cloud-Tickler** [comment]
Hey Pascal,
now I had the chance to try it. Works perfectly.
Thanks a lot.
Happy printing.
Regards
Dennis
![2023-08-29 19_31_47-OctoPrint](https://github.com/RealTryZ/Wattometer/assets/127838436/913dfdd3-0116-4d3a-81a6-c798551f631a)

**Comment by RealTryZ** [comment]
> Hey Pascal,
> now I had the chance to try it. Works perfectly.
> Thanks a lot.
> Happy printing.
> Regards
> Dennis
> ![2023-08-29 19_31_47-OctoPrint](https://github.com/RealTryZ/Wattometer/assets/127838436/913dfdd3-0116-4d3a-81a6-c798551f631a)
> 

Hey Dennis, 
glad to hear that.
Happy printing too.
